logging:
    level:
        root: info
        com:
            free:
                agent:
                    db: DEBUG
spring:
    application:
        name: free-agent
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/free_llm_db?TimeZone=Asia/Shanghai
        username: ENC(RgoixuWhvO+/bTbgWNQCOR9nNc1ItiZ7C3LzC26AN/Mvtq1FmyFDAP50pptZ0KZk)
        password: ENC(z/mwhIGSWfKuLZ9YghP/jiQ9sjn2nOn5jnq5+q0qDfG8zghS5K8GENKgR9iP/hYN)
        type: com.zaxxer.hikari.HikariDataSource
        Hikari:
            # 连接池中允许的最小连接数。缺省值：10
            minimum-idle: 10
            # 连接池中允许的最大连接数。缺省值：10
            maximum-pool-size: 15
            # 自动提交
            auto-commit: true
            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
            idle-timeout: 600000
            # 连接池名字
            pool-name: YIXGHikariCP
            # 一 个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
            max-lifetime: 1800000
            # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLExcepti on， 缺省:30秒
            connection-timeout: 30000
embedding-store:
    elasticsearch:
        enable: true
        hostname: localhost
        port: 9200
        scheme: https
        user-name: elastic
        pass-word: 123456
        index-name: free_llm_embedding
        dimension: 1024
minio:
    url: http://127.0.0.1:9000
    access-key: ENC(N2icJuGi5fCuPCrNEC4ft7Tg1dGj7M16KvydkwQgF1Go3mgFcZPcohpPG2P220QQ)
    secret-key: ENC(eZZ0bVmrg697PAzWY/VXpvzR119lWxNxCLxRyyemXyrb0G54EwYhLf5vwfYPgJFutrLrp2/mNlIw2vw5k+fpcw==)
zhipu-ai-embedding-model:
    api-key: ENC(Rd7ystSTbB0JYyf6KCXXLhrXLtR7hMq7dvRhpoJI1y1YDIAhvfdwyNCiEashKr7m/I8aj+SZv3Ehrkz5VOpuvliafFJA7WuudWHSLbktaEde8eDLfpnNFuCcJWg0RHCM)
    max-retries: 1
    model: embedding-2
    log-requests: true
    log-responses: true

zhipu-ai-chat-model:
    api-key: ENC(Rd7ystSTbB0JYyf6KCXXLhrXLtR7hMq7dvRhpoJI1y1YDIAhvfdwyNCiEashKr7m/I8aj+SZv3Ehrkz5VOpuvliafFJA7WuudWHSLbktaEde8eDLfpnNFuCcJWg0RHCM)
    model:



