spring:
    application:
        name: free-agent
embedding-store:
    elasticsearch:
        enable: false
        hostname: localhost
        port: 9200
        scheme: https
        user-name: elastic
        pass-word: 123456
        index-name: llm_vector
        dimension: 384